---
- name: Add EPEL repository
  yum:
    name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Upgrade OS
  yum:
    name: '*'
    state: latest
    update_cache: true

- name: Install tools 
  yum:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
    - yum-utils
    - net-tools
    - htop
    - iotop
    - vim
    - nano
    - mc
    - sudo
    - nfs-utils
    - device-mapper-persistent-data
    - lvm2
    - which

- name: Change Hostname
  hostname:
    name: "{{ hostname }}"

- name: Check if Firewalld Exists
  stat: path=/etc/firewalld/firewalld.conf
  register: service_status

- name: Stop firewall
  service: 
    name: firewalld
    enabled: no
    state: stopped
  when: service_status.stat.exists
  register: service_stopped
     
- name: Install NTP
  yum:
    name: ntp
    state: present

- name: Start NTP
  service: 
    name: ntpd
    state: started
    enabled: yes

- name: Check if SELinux is installed
  stat: 
    path: /etc/selinux/config
  register: selinux_config_file
    
- name: Disable SELinux on reboot
  selinux:
    state: disabled
  when: selinux_config_file.stat.exists

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

# - name: Enable bridge-nf-call tables
#   sysctl:
#     name: "{{ item }}"
#     state: present
#     value: 1
#     reload: yes
#   with_items:
#     - net.bridge.bridge-nf-call-iptables
#     - net.bridge.bridge-nf-call-arptables
#     - net.bridge.bridge-nf-call-ip6tables
