---
- name: Add EPEL repository
  yum:
    name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
    use_backend: yum

- name: Upgrade OS
  yum:
    name: '*'
    state: latest
    update_cache: true
    use_backend: yum

- name: Install tools 
  yum:
    name: net-tools, htop, iotop, vim, nano, mc, firewalld, sudo, nfs-utils
    state: installed
    use_backend: yum

- name: Change Hostname
  hostname:
    name: "{{ hostname }}"

- name: Stop firewall
  service: 
    name: firewalld
    enabled: no
    state: stopped
     
- name: Install NTP
  yum:
    name: ntp
    state: present
    use_backend: yum

- name: Start NTP
  service: 
    name: ntpd
    enabled: yes
    state: started

- name: Check if SELinux is installed
  stat: 
    path: /etc/selinux/config
  register: selinux_config_file
    
- name: Disable SELinux on reboot
  selinux:
    state: disabled
  when: selinux_config_file.stat.exists

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

# - name: Enable bridge-nf-call tables
#   sysctl:
#     name: "{{ item }}"
#     state: present
#     value: 1
#     reload: yes
#   with_items:
#     - net.bridge.bridge-nf-call-iptables
#     - net.bridge.bridge-nf-call-arptables
#     - net.bridge.bridge-nf-call-ip6tables

- name: Add Kubernetes YUM repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes