---
- name: Add EPEL repository
  yum:
    name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Upgrade OS
  yum:
    name: '*'
    state: latest
    update_cache: true

- name: Install network managment packages
  yum:
    name: python-gobject, NetworkManager-glib, net-tools
    state: installed

- name: Install tools 
  yum:
    name: net-tools, htop, iotop, vim, nano, mc
    state: installed

- name: Change Hostname
  hostname:
    name: "{{ hostname }}"

- name: Stop firewall
  service: 
    name: firewalld
    enabled: no
    state: stopped
     
- name: Install NTP
  yum:
    name: ntp
    state: present

- name: Start NTP
  service: 
    name: ntpd
    enabled: yes
    state: started

- name: Setup Network Adapter
  nmcli:
    conn_name: eth1
    autoconnect: yes
    ifname: eth1
    type: ethernet
    ip4: "{{ ansible_host }}"
    gw4: "{{ gateway }}"
    dns4: "{{ dns }}"
    state: present

- name: Add IP address of all hosts to host file
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].hostname }}"
    state: present
  with_items: "{{ groups.all }}"

- name: disable SELinux
  command: setenforce 0

- name: disable SELinux on reboot
  selinux:
    state: disabled

- name: Disable swap
  command: swapoff -a

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Enable bridge-nf-call tables
  sysctl:
    name: "{{ item }}"
    state: present
    value: 1
    reload: yes
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-arptables
    - net.bridge.bridge-nf-call-ip6tables

- name: Add Kubernetes YUM repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes