---
- name: Ensure NFS common is installed.
  yum: 
    name: "{{ packages }}"
    state: installed 
    update_cache: yes
  vars:
    packages:
    - nfs-utils

- name: Create mountable dir
  file: 
    path: /nfs 
    state: directory
    mode: '0777'
    owner: root
    group: root

- name: set mountpoints
  become: yes
  mount: 
    path: /nfs 
    src: "{{ hostvars[groups['nfs-share'][0]].ansible_host }}:/nfs"
    fstype: nfs
    opts: defaults
    passno: '2'
    state: mounted