apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: grafana
  labels:
    tier: webservice
    application: grafana  
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: webservice
      application: grafana
  template:
    metadata:
      labels:
        tier: webservice
        application: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: data
        ports:
          - containerPort: 3000
            protocol: TCP
      restartPolicy: Always
      volumes:
        - emptyDir: {}
          name: data
      
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana
  labels:
    tier: webservice
    application: grafana 
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 32091
      targetPort: 3000
      name: http
  selector:
    tier: webservice
    application: grafana