apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: monitoring
  name: prometheus
  labels:
    tier: webservice
    application: prometheus  
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: webservice
      application: prometheus
  template:
    metadata:
      labels:
        tier: webservice
        application: prometheus
    spec:
      containers:
      - name: prometheus
        image: quay.io/coreos/prometheus:0.19.2
        args:
          - '-storage.local.retention=6h'
          - '-storage.local.memory-chunks=500000'
          - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: prometheus
  labels:
    tier: webservice
    application: prometheus
spec:
  type: NodePort
  ports:
  - port: 9090
    nodePort: 32090
    targetPort: 9090
    name: http
  selector:
    tier: webservice
    application: prometheus

