apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
    scrape_configs:
    # etcd is living outside of our cluster and we configure
    # it directly.
    - job_name: 'Nodes'
      target_groups:
      - targets:
        - 192.168.99.107:9100