ENV['VAGRANT_PARALLEL'] = 'yes'

bridge_adapter = "eth0"
box_image = "centos/7"
CPU = 2
MEMORY = 4096

Vagrant.configure("2") do |config|
    
  config.vm.define "kubernetes-master" do |master|
    master.vm.box = box_image
    master.vm.hostname  = "kubernetes-master"
    master.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    master.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
    master.ssh.insert_key = false
    master.vm.provider "virtualbox" do |vb|
      hyperv.memory = MEMORY
      hyperv.vmname = "kubernetes-master"
      hyperv.cpus = CPU
    end
  end

  NodeCount = 2

  (1..NodeCount).each do |i|
    config.vm.define "kubernetes-worker#{i}" do |worker|
      worker.vm.box = box_image
      worker.vm.hostname = "kubernetes-worker#{i}"
      worker.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
      worker.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
      worker.ssh.insert_key = false
      worker.vm.provider "virtualbox" do |vb|
        hyperv.memory = MEMORY
        hyperv.vmname = "kubernetes-worker#{i}"
        hyperv.cpus = CPU
      end
    end
  end
end