---
- name: Check if kubeadm was inicialized
  stat: path=/etc/kubernetes/manifests/kube-apiserver.yaml
  register: kubeadm_status

- name: Revert kubeadm changes
  become: yes
  shell: kubeadm reset --force
  when: kubeadm_status.stat.exists

- name: Initialize the cluster
  become: yes
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ hostvars[groups['masters'][0]].ansible_host }}
  args:
    chdir: $HOME

- name: create .kube directory
  become_user: "{{ ansible_user }}"
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to user's kube config
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"

- name: get join command
  shell: kubeadm token create --print-join-command 
  register: join_command_raw

- name: set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Install Pod network
  become_user: "{{ ansible_user }}"
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  args:
    chdir: $HOME
    creates: pod_network_setup.txt