apiVersion: v1
kind: Namespace
metadata:
  name:  mysql

---
apiVersion: v1
kind: Secret
metadata:
  name:  mysql
  namespace: mysql
type: Opaque
data:
  mysql_root_password: YXNkenhj 
#password: asdzxc

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: mysql
  name: mysql-server
  labels:
    service: mysql
    application: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      application: mysql
  template:
    metadata:
      labels:
        application: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              # value: 'asdzxc'
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: mysql_root_password
          ports:
           - containerPort: 3306
             name: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mysql
  name: phpmyadmin
  labels:
    service: mysql
    application: phpmyadmin
spec:
  replicas: 2
  selector:
    matchLabels:
      application: phpmyadmin
  template:
    metadata:
      labels:
        application: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        imagePullPolicy: Always
        env:
          - name: PMA_HOST
            value: mysql
          - name: PMA_PORT
            value: '3306'
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: mysql
spec:
  selector:
    application: phpmyadmin
  type: NodePort
  ports:
  - port: 80
    targetPort: 80

        