kind: Deployment
apiVersion: apps/v1beta2
metadata:
  namespace: mysql
  name: phpmyadmin-server
  labels:
    application: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      application: phpmyadmin
  template:
    metadata:
      labels:
        application: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: bitnami/phpmyadmin:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: mysql_root_password
            - name: DATABASE_HOST
              value: "mysql-service"
            - name: DATABASE_PORT_NUMBER
              value: "3306"
          ports:
            - containerPort: 80
              name: phpmyadmin

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: mysql
  labels:
    application: phpmyadmin
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    application: phpmyadmin