apiVersion: v1
kind: Pod
metadata:
  namespace: mysql
  name: mysql-server
  labels:
    application: mysql
spec:
  containers:
    - name: mysql
      image: mysql:5
      imagePullPolicy: Always
      env:
        - name: "MYSQL_ROOT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql
              key: mysql_root_password
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      resources:
        requests:
          memory: "256Mi"
          cpu: "256m"
        limits:
          memory: "512Mi"
          cpu: "500m"
  volumes:
    - name: mysql-storage
      persistentVolumeClaim:
        claimName: mysql-pv-claim