kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local
provisioner: kubernetes.io/fake-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv02/