---
- name: Check if kubeadm was inicialized
  stat: 
    path: /etc/kubernetes/kubelet.conf
  register: kubeadm_status

- name: Revert kubeadm changes
  become: yes
  shell: kubeadm reset --force
  when: kubeadm_status.stat.exists

- name: join cluster
  shell: "{{ hostvars[groups['masters'][0]].join_command }}"
  args:
    chdir: $HOME