kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs
provisioner: kubernetes.io/fake-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  namespace: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /STORAGE
    server: 192.168.1.123