---
- name: Install kubelet
  yum:
    name: kubelet
    state: present
    update_cache: true

- name: Disable fail SWAP in kubelet
  become: yes
  shell: echo 'KUBELET_EXTRA_ARGS="--fail-swap-on=false"' > /etc/sysconfig/kubelet

- name: Install kubeadm
  yum:
    name: kubeadm
    state: present

- name: Start kubelet
  service:
    name: kubelet
    enabled: yes
    state: started