---
- name: Prepare Kubernetes hosts
  become: yes
  hosts: all
  gather_facts: false
  roles:
    - common

- name: Prepare Kubernetes nodes
  become: yes
  hosts: cluster
  gather_facts: false
  roles: 
    - docker
    - kubernetes

- name: Configure Kubernetes Master node
  become: yes
  hosts: masters
  gather_facts: false
  roles:
    - kubernetes-master

- name: Configure Kubernetes Worker node
  become: yes
  hosts: workers
  gather_facts: false
  roles:
    - kubernetes-worker

- name: Configure Persistent Storage
  become: yes
  hosts: nfs-share
  gather_facts: false
  roles:
    - nfs-server