---
- hosts: cluster
  become: yes
  tasks:
    - name: Add EPEL repository
      yum:
        name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: Upgrade OS
      yum:
        name: '*'
        state: latest
        update_cache: true

    - name: Install network managment packages
      yum:
        name: python-gobject, NetworkManager-glib, net-tools
        state: installed

    - name: Install tools 
      yum:
        name: net-tools, htop, iotop, vim, nano, mc
        state: installed

    - name: Change Hostname
      hostname:
        name: "{{ hostname }}"

    - name: Stop firewall
      service: 
        name: firewalld
        enabled: no
        state: stopped
       
    - name: Install ntp
      yum:
        name: ntp
        state: present

    - name: start ntp
      service: 
        name: ntpd
        enabled: yes
        state: started

    - name: setup NIC
      nmcli:
        conn_name: eth1
        autoconnect: yes
        ifname: eth1
        type: ethernet
        ip4: "{{ ansible_host }}"
        gw4: "{{ gateway }}"
        dns4: "{{ dns }}"
        state: present